import { Metadata } from "next";
import AuthBtn from "@/app/(component)/AUTH";
// import {
//   Card,
//   CardContent,
//   CardHeader,
//   CardFooter,
// } from "@/components/ui/card";
// import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
// const font = Poppins({
//   fallback: [""],
//   style: ["italic"],
//   subsets: ["latin"],
//   preload: true,
//   weight: ["600"],
// });
export const metadata: Metadata = {
 title: "marketplace",
 description: "Generated by Me",
};

export default function MarketLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  //   <div className="px-10 bg-slate-400 m-2 shadow-md w-full h-full ">
  <div className="w-full min-h-full   px-10  bg-slate-400 shadow-md">
   <header className="flex flex-col ">
    <h1 className={cn("text-3xl text-center  ", "font-serif")}>
     Welcome to Marketplace
    </h1>
    <AuthBtn />
   </header>
   <div className="m-2">{children}</div>
  </div>
 );
}
