import { Metadata } from "next";
import AuthBtn from "@/app/(component)/AUTH";
import {
  Card,
  CardContent,
  CardHeader,
  CardFooter,
} from "@/components/ui/card";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
const font = Poppins({
  fallback: [""],
  style: ["italic"],
  subsets: ["latin"],
  preload: true,
  weight: ["600"],
});
export const metadata: Metadata = {
  title: "marketplace",
  description: "Generated by Me",
};

export default function MarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Card className="px-10  shadow-md w-full h-full ">
      <CardHeader className="flex flex-col ">
        <h1 className={cn("text-3xl text-center  ", font.className)}>
          Welcome to Marketplace
        </h1>
        <AuthBtn />
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}
