import { Metadata } from "next";
import Navbar from "../(component)/Navbar";

export const metadata: Metadata = {
  title: "Market AdminPanel",
  description: "Generated by Me",
};

export default function MarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-full bg-slate-700 w-full ">
      <Navbar />

      {children}
    </div>
  );
}
