import { Metadata } from "next";
import Navbar from "../(component)/Navbar";
import AuthBtn from "../(component)/AUTH";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Market AdminPanel",
  description: "Generated by Me",
};

export default async function MarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session?.user.role !== "admin") redirect("/");
  return (
    <div className="flex h-full bg-slate-700 w-full ">
      <Navbar />

      {children}
    </div>
  );
}
